name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: pip install -r requirements.txt